name: Build

on: [push, pull_request]

jobs:

  build:

    name: Build on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    env:
      APKTOOL_VERSION: 2.4.1

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Set up Java
#        uses: actions/setup-java@v1
#        with:
#          version: 8.0.x

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Install dependencies (Ubuntu)
        if: contains(matrix.os, 'ubuntu') == true
        shell: bash
#        env:
#          ANDROID_HOME: /android-sdk
        run: |
          # Install Apktool.
          sudo wget -q https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O /usr/local/bin/apktool
          sudo chmod a+x /usr/local/bin/apktool
          sudo wget -q "https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_${APKTOOL_VERSION}.jar" -O /usr/local/bin/apktool.jar
          sudo chmod a+x /usr/local/bin/apktool.jar

      - name: Install dependencies (Windows)
        if: contains(matrix.os, 'windows') == true
        shell: powershell
#        env:
#          ANDROID_HOME: C:\android-sdk
        run: |
          # Install Apktool.
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/windows/apktool.bat -OutFile C:\Windows\apktool.bat
          wget "https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_$env:APKTOOL_VERSION.jar" -OutFile C:\Windows\apktool.jar

      - name: Install dependencies (MacOS)
        if: contains(matrix.os, 'macOS') == true
        shell: bash
#        env:
#          ANDROID_HOME: /android-sdk
        run: |
          # Install Apktool.
          sudo wget -q https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/osx/apktool -O /usr/local/bin/apktool
          sudo chmod a+x /usr/local/bin/apktool
          sudo wget -q "https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_${APKTOOL_VERSION}.jar" -O /usr/local/bin/apktool.jar
          sudo chmod a+x /usr/local/bin/apktool.jar

      - name: Check installation
        if: contains(matrix.os, 'windows') == false
        shell: bash
#        env:
#          ANDROID_HOME: /android-sdk
        run: |
          cd src
          python -m obfuscapk.cli --help

      - name: Check installation (Windows)
        if: contains(matrix.os, 'windows') == true
        shell: powershell
#        env:
#          ANDROID_HOME: C:\android-sdk
        run: |
          cd src
          python -m obfuscapk.cli --help
